#!/usr/bin/env python3
"""
post.py — turn a nail sequence (JSON from generator/stringart.py) into G-code for a
Bart Dring style rotating-platter string art machine running FluidNC / Grbl_ESP32.

Machine model (see DESIGN.md):
  X  = platter rotation, configured in NAIL UNITS (1.0 = one nail pitch), so the
       steps/mm you set in FluidNC is really steps-per-nail.  The number of nails
       comes from the JSON, so changing the nail count only changes that one number
       in the controller config (see fluidnc-config.yaml).
  Y  = radial thread arm.  Y_OUT is extended (thread guide outside the nail ring),
       Y_IN is retracted (inside the ring).
  Z  = optional drill axis for making the nail holes (--drill).

Wrap macro per nail, from Dring's string_post.py:
  G0 X{pin+0.5} Y{out}   approach one side of the nail with the arm extended
  G0 Y{in}               retract past the nail
  G0 X{pin-0.5}          rotate half a pitch back, thread is now behind the nail
  G0 Y{out}              extend again: the thread has looped the nail

Rotation direction: by default the platter turns the shortest way to the next nail
and X is emitted as an unwrapped, ever-accumulating coordinate (turn off soft limits
on X).  Use --no-shortest to keep X inside [0, nails) and always turn one way.

Usage:
  python post.py ../generator/out/lincoln.json                 -> lincoln.gcode
  python post.py ../generator/out/lincoln.json --drill         -> lincoln_drill.gcode
"""

import argparse
import json
import os


def wrap_moves(pin: float, y_out: float, y_in: float, half: float):
    return [
        f"G0 X{pin + half:.3f} Y{y_out:.3f}",
        f"G0 Y{y_in:.3f}",
        f"G0 X{pin - half:.3f}",
        f"G0 Y{y_out:.3f}",
    ]


def thread_gcode(seq, nails, y_out, y_in, half, feed_x, feed_y, shortest, home, start_pause):
    g = [
        "; string art thread path generated by machine/post.py",
        f"; nails={nails} lines={len(seq) - 1}",
        "; X in nail units, Y in mm",
        "G21 ; mm",
        "G90 ; absolute",
        "G94 ; units per minute feed",
    ]
    if home:
        g.append("$H ; home all")
    g.append(f"G10 L20 P0 X0 Y{y_out:.3f} ; nail 0 is under the arm, arm extended")
    g.append(f"G1 F{feed_x:.0f}")
    g.append(f"G0 Y{y_out:.3f}")
    g.append(f"G0 X0")
    if start_pause:
        g.append("M0 ; tie the thread to nail 0, then resume")

    x_abs = 0.0  # unwrapped platter position in nail units
    for k, pin in enumerate(seq):
        if shortest:
            # move to the equivalent of `pin` closest to the current unwrapped position
            delta = (pin - x_abs) % nails
            if delta > nails / 2:
                delta -= nails
            target = x_abs + delta
        else:
            target = float(pin)
        g.append(f"; line {k}: nail {pin}")
        g.extend(wrap_moves(target, y_out, y_in, half))
        x_abs = target - half  # the wrap leaves the platter at pin - half

    g.append("M0 ; tie off and cut the thread")
    g.append("M2")
    return "\n".join(g) + "\n"


def drill_gcode(nails, z_safe, z_depth, feed_z, spindle):
    g = [
        "; nail hole drilling generated by machine/post.py",
        f"; nails={nails}",
        "G21", "G90", "G94",
        f"G0 Z{z_safe:.3f}",
        f"M3 S{spindle:.0f}",
        "G4 P2 ; let the drill spin up",
    ]
    for pin in range(nails):
        g.append(f"G0 X{pin}")
        g.append(f"G1 Z{z_depth:.3f} F{feed_z:.0f}")
        g.append(f"G0 Z{z_safe:.3f}")
    g.append("M5")
    g.append("M2")
    return "\n".join(g) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("sequence_json")
    ap.add_argument("-o", "--output", default=None, help="output .gcode path")
    ap.add_argument("--y-out", type=float, default=28.0, help="arm extended position, mm")
    ap.add_argument("--y-in", type=float, default=0.0, help="arm retracted position, mm")
    ap.add_argument("--half", type=float, default=0.5, help="overshoot each side of the nail, in nail units")
    ap.add_argument("--feed-x", type=float, default=3000.0, help="feed for G1 moves (G0 uses max rate)")
    ap.add_argument("--feed-y", type=float, default=3000.0)
    ap.add_argument("--no-shortest", action="store_true", help="always rotate one way, keep X in [0,nails)")
    ap.add_argument("--no-home", action="store_true", help="do not emit $H")
    ap.add_argument("--no-start-pause", action="store_true", help="do not emit M0 for tying on the thread")
    ap.add_argument("--drill", action="store_true", help="emit the hole-drilling program instead")
    ap.add_argument("--z-safe", type=float, default=10.0)
    ap.add_argument("--z-depth", type=float, default=-9.0)
    ap.add_argument("--feed-z", type=float, default=1600.0)
    ap.add_argument("--spindle", type=float, default=1000.0)
    args = ap.parse_args()

    with open(args.sequence_json) as f:
        data = json.load(f)
    nails = int(data["nails"])
    seq = [int(s) for s in data["sequence"]]

    base = os.path.splitext(os.path.basename(args.sequence_json))[0]
    if args.drill:
        text = drill_gcode(nails, args.z_safe, args.z_depth, args.feed_z, args.spindle)
        out = args.output or f"{base}_drill.gcode"
    else:
        text = thread_gcode(seq, nails, args.y_out, args.y_in, args.half, args.feed_x, args.feed_y,
                            not args.no_shortest, not args.no_home, not args.no_start_pause)
        out = args.output or f"{base}.gcode"
    with open(out, "w") as f:
        f.write(text)
    print(f"wrote {out}: {nails} nails, {len(seq) - 1 if not args.drill else nails} {'holes' if args.drill else 'lines'}")


if __name__ == "__main__":
    main()
